---
- name: Update Vault AppRole Secret ID in AAP Credential
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Update AAP Credential with new Vault Secret ID
      ansible.controller.credential:
        controller_host: "{{ aap_url }}"                    # URL of your AAP instance
        controller_oauthtoken: "{{ aap_token }}"            # AAP OAuth token
        name: "GCVE Vault Credential Config"                # Name of the credential
        description: "Credential for HashiCorp Vault AppRole integration"
        organization: "Default"                             # Organization name in AAP
        credential_type: "HashiCorp Vault Signed SSH"       # Type of the credential
        state: present                                      # Ensures the credential is updated or created if absent
        inputs:                                             # All required fields for this credential type
          url: "{{ vault_url }}" # Server URL (VAULT_ADDR)
          cacert: "{{ vault_ca_cert_base64 }}"                    # CA Certificate if applicable
          role_id: "{{ vault_role_id }}"                    # Vault AppRole role_id
          secret_id: "{{ vault_secret_id }}"                # Vault AppRole secret_id
          default_auth_path: "approle"                              # Path to the Vault AppRole auth method
        validate_certs: false                               # Skip SSL verification if using self-signed certs
      register: credential_update

    - name: Display Credential Update Status
      debug:
        msg: "Credential update response: {{ credential_update }}"
