---
- name: Update Vault AppRole Secret ID in AAP Credential
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Update AAP Credential with new Vault Secret ID
      ansible.controller.credential:
        controller_host: "{{ aap_url }}"                     # URL of AAP Controller
        controller_oauthtoken: "{{ aap_token }}"             # AAP OAuth token for authentication
        name: "Vault SSH Credential"                         # Name of the credential in AAP
        credential_type: "HashiCorp Vault Signed SSH"        # Specify the correct credential type
        organization: "{{ organization }}"                   # AAP organization owning the credential
        state: present
        inputs:
          secret_id: "{{ vault_secret_id }}"                 # New Vault secret_id to update
      register: credential_update

    - name: Display Credential Update Status
      debug:
        msg: "Credential update response: {{ credential_update }}"
